### PR TITLE
[write] restore `sep` functionality. closes #1199

### LINKED ISSUE #1199: `wb_add_data()` errors when `x` contains list columns
Please correct me if I'm wrong but it looks like the `sep` argument is not implemented. As a result, `wb_add_data()` errors when `x` contains list columns. Here is an example to illustrate the issue:

``` r
library(openxlsx2)

tbl <- tibble::tibble(
  "CharCol" = LETTERS,
  "ListCol" = lapply(
    LETTERS, \(x) {
      sample(LETTERS, replace = TRUE, size = 5)
      }
  )
)

wb_workbook() |> 
  wb_add_worksheet() |> 
  wb_add_data(
    x = tbl
  )
#> Error: Not compatible with STRSXP: [type=list].

packageVersion("openxlsx2")
#> [1] '1.11.0.9000'
```

<sup>Created on 2024-12-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by JanMarvin**
Previously this was only documented but did nothing

### CODE REVIEW

File: src/openxlsx2_types.h [hunk 1]
```diff
@@ -55,6 +56,7 @@ enum celltype {
 #include <Rcpp.h>
 #endif
 
+
```
Comment (JanMarvin) [inline src/openxlsx2_types.h:59]: unintended change
